# Generated by Django 4.0.6 on 2022-07-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('jobdetailurl', models.CharField(max_length=250)),
                ('jobtitle', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SearchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=250)),
                ('total_div', models.IntegerField()),
            ],
        ),
    ]
